Домашняя работа 15
BrakhmaQA/country-st5 pull request #1
Opened 2024-07-18 21:07 UTC by BrakhmaQA

2024-07-19 06:44 UTC, sashkir7 requested changes
Добрый день
Не доделали работу до конца. Необходимо внести ряд правок - более детально написал в комментариях к PR

2024-07-19 06:44 UTC, sashkir7 commented on src/main/java/guru/qa/country/controller/CountryController.java
> +@RequestMapping("/db/migration/country")
А почему такой базовый endpoint? При чем здесь migration?
Почему не просто, например, country?

2024-07-19 06:44 UTC, sashkir7 commented on src/main/java/guru/qa/country/data/CountryEntity.java
> +@Table(schema = "db/migration/country")
И здесь тоже, думаю, что ввели что-то не то. 
Для чего так называть схему в бд?

2024-07-19 06:44 UTC, sashkir7 commented on src/main/java/guru/qa/country/service/CountryService.java
> +    }
Методы в сервисе есть - это хорошо
Но они нигде не используются - в чем тогда их смысл? 
Вы забыли добавить "ручки" в контроллер

2024-07-19 06:44 UTC, sashkir7 commented on src/main/java/guru/qa/country/controller/CountryController.java
> +    }
То есть у нас есть единственная ручка в текущем сервисе?
Это не совсем правильно - их должно быть сильно больше

2024-07-19 14:22 UTC, BrakhmaQA commented on src/main/java/guru/qa/country/controller/CountryController.java
> +@RequestMapping("/db/migration/country")
Сам не знаю как так получилось)

2024-07-19 14:22 UTC, BrakhmaQA commented on src/main/java/guru/qa/country/data/CountryEntity.java
> +@Table(schema = "db/migration/country")
Тут тоже не пойму как получилось)

2024-07-19 14:23 UTC, BrakhmaQA commented on src/main/java/guru/qa/country/service/CountryService.java
> +    }
Действительно забыл, поторопился

2024-07-19 14:23 UTC, BrakhmaQA commented on src/main/java/guru/qa/country/controller/CountryController.java
> +    }
Добавил

2024-07-21 17:24 UTC, sashkir7 approved these changes
Ага, теперь хорошо - похоже на правду =)

2024-07-21 20:12 UTC, merged